/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cprice.kotlin_aws_sdk.ktor.leak

import aws.sdk.kotlin.services.sqs.SqsClient
import kotlinx.coroutines.asCoroutineDispatcher
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import java.util.concurrent.Executors
import kotlin.time.Duration.Companion.seconds

fun main() {
    val sqsQueueUrl = System.getenv("SQS_QUEUE_URL") ?: throw IllegalStateException("Missing required env var SQS_QUEUE_URL")

    runBlocking {
        val sqsClient = SqsClient {
            this.region = "us-west-2"
        }

        val dispatcher = Executors.newFixedThreadPool(1).asCoroutineDispatcher()

        launch(dispatcher) {
            while (true) {
                println("Delaying for 0.25s")
                delay(0.25.seconds)
                println("Making SQS api call")
                val response = sqsClient.receiveMessage {
                    this.queueUrl = sqsQueueUrl
                }
                println("SQS response: $response")
            }
        }
    }
}
